config/routes.rb
Bob::Application.routes.draw do

  devise_for :users

  resources :dashboards
  resources :projects
  resources :builds
  resources :users

  match "/projects/:id/build", :to => "projects#build",:as=> :build_project
  match "/projects/:id/delete_step", :to => "projects#delete_step", :as => :delete_step
  match "/build/:id/status", :to => "builds#build_status", :as => :build_status
  match "/list", :to => "builds#latest_builds", :as => :latest_builds
  match "/list(/:id)", :to => "builds#latest_by_project", :as => :latest_by_project

  resources :service do
    post 'github'
  end

  root :to => "dashboards#index"
end

app/models/build.rb
class Build
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Stateflow
  include Rails.application.routes.url_helpers

  # fields
  field :state,         :type => String
  field :started_at,    :type => Time
  field :completed_at,  :type => Time

  referenced_in     :project
  references_many   :commits, :inverse_of => :build, :dependent => :destroy
  references_many   :build_steps, :inverse_of => :build, :dependent => :destroy

  before_create :associate_commits
  after_destroy :remove_build_dir

  # on state change, handle running hooks
  stateflow do
    initial :pending

    state :pending

    state :building do
      enter :processing_build
    end

    state :failed do
      enter :failed_build
    end

    state :success do
      enter :successful_build
    end

    event :build do
      transitions :from => :pending,  :to => :building
      transitions :from => :failed,   :to => :building
      transitions :from => :success,  :to => :building
    end 

    event :build_completed do
      transitions :from => :building, :to => :success
    end

    event :build_failed do
      transitions :from => :building, :to => :failed
    end

  end


  def processing_build
    self.build_steps.delete_all # just in case...we don't want them lingering
    self.update_attributes(:started_at => Time.now.utc) 
  end

  def failed_build
    self.update_attributes(:completed_at => Time.now.utc)

    # do the hooks
    self.project.campfire.send_failed(self) if self.project.campfire.post_message?
  end

  def successful_build
    # Hook needs moved
    self.update_attributes(:completed_at => Time.now.utc)

    # do the hooks
    self.project.campfire.send_success(self) if self.project.campfire.post_message?
  end

  def associate_commits
    self.project.commits.untested.each do |commit|
      commit.update_attributes(:build => self) 
    end
  end

  def branch_name
    (self.latest_commit.nil? or self.latest_commit.branch.nil?) ? self.project.branch_name : self.latest_commit.branch
  end

  def build_dir
    File.join(Rails.root, 'tmp', 'builds', self.id.to_s)
  end

  # process the build
  def perform
    # Change state to building 
    build!

    Rails.logger.debug("[BOB] running perform for build #{self.id}.")

    scm = project.scm_type.constantize
    checkout = scm.checkout(self)
    steps = project.steps.clone
    steps.unshift(Step.new(:name => 'Code Checkout', :command => checkout))

    # Make the build dir
    FileUtils.mkdir_p(self.build_dir)

    steps.each_with_index do |step, index|
      build_step = BuildStep.new
      build_step.name = step.name
      build_step.build = self
      build_step.command = step.command
      build_step.save
      build_step.build_step!

      # get any commit info we can 
      if !commits.present? and index == 1
        scm.build_commit(self)
      end

      begin
        result = Runner.run(build_dir, step.formatted_command)
        # change state to completed
        build_step.output = result
        build_step.step_completed!
      rescue ::RunnerError => e
        # change state to failed
        build_step.output = e.output
        build_step.step_failed!
        build_step.save
        Rails.logger.debug(e.message)
        break
      end
    end

    Build.delay.clean_old_builds(project.id)
    Rails.logger.debug("[BOB] checking for pending builds....")
    Build.delay.run_pending_builds(self.project)
    has_failure? ? build_failed! : build_completed!
  end

  def self.run_pending_builds(project)
    found = Build.where(:project_id => project.id, :state => :pending)
    Rails.logger.debug("[BOB] found #{found.count} pending builds...")
    found.each do |build|
      build.destroy! unless build == found.last
      build.delay.perform if build == found.last
    end
  end

  def has_failure?
    (self.build_steps.where(:state => :failed).count >= 1) ? true : false
  end

  def duration
    self.completed_at - self.started_at
  end

  def remove_build_dir
    FileUtils.rm_rf(self.build_dir)
  end

  def steps_completed
    done = build_steps.where(:state => 'success').count
    (done - 1)
  end

  def latest_commit
    commits.last
  end

  def as_json(options={})
    completed_steps = (steps_completed <= 0) ? 'waiting' : steps_completed
    commit_id = self.latest_commit.nil? ?  "waiting" : self.latest_commit.guid

    if self.commits.count > 0
      commit_url = self.latest_commit.url.nil? ? latest_commit.guid : latest_commit.url
      commit_message = self.latest_commit.message.nil? ? 'waiting' : latest_commit.message  
      commit_guid = self.latest_commit.guid.nil? ? 'waiting' : latest_commit.guid
    end
   
    started = self.started_at.nil? ? "waiting" : self.started_at.strftime("%m/%d/%Y %H:%I %p")
    completed = self.completed_at.nil? ? "waiting" : self.completed_at.strftime("%m/%d/%Y %H:%I %p")
    created = self.created_at.nil? ? "waiting" : self.created_at.strftime("%m/%d/%Y %H:%I %p")

    {
      :id => self.id,
      :project_name => self.project.name,
      :project_id => self.project.id,
      :project_slug => self.project.slug,
      :commit_message => commit_message,
      :state => self.state,
      :completed_at => completed,
      :created_at => created,
      :started_at => started,
      :commit_id => commit_guid,
      :total_steps => self.project.steps.count,
      :steps_completed => completed_steps,
      :commit_url => commit_url
    }
  end

  class << self
    def clean_old_builds(project)
      project = Project.find(project)
      build_count = project.keep_build_count ||= 10
      old_builds = self.order_by(:created_at.desc).skip(build_count)
      old_builds.each do |build|
        build.destroy
      end
    end
  end

end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController

  #before_filter :find_build, :except => [:latest_builds, :latest_builds_by_project]
  before_filter :find_build, :only => [:show, :destroy]

  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to(root_url) }
    end
  end

  def show
  end

  def build_status
    render :partial => "build", :layout => false, :locals => {:build => @build}
  end

  def latest_builds
    @builds = Build.desc(:created_at).limit(10)
    respond_to do |format|
      format.json { render :json => @builds.as_json }
    end
  end

  def latest_by_project
    project = Project.where(:slug => params[:id]).first
    @builds = Build.where(:project_id => project.id).desc(:created_at).limit(10)
    respond_to do |format|
      format.json { render :json => @builds.as_json }
    end
  end

  def find_build
    @build = Build.find(params[:id])
  end
  private :find_build

end

app/views/builds/_build.html.haml
.block{:class => build.state, :id => build.id}
  .block_head
    .bheadl
    .bheadr
    %h2
      = build.project.name
      = image_tag('lock.png') if build.project.private
    %span.ajax-loading
    %ul
      - if can? :read, build.project
        %li
          = link_to "Project View", dashboard_path(build.project.slug) 
      - if can? [:edit, :update], build.project
        %li
          = link_to "Edit Project", edit_project_path(build.project)
      %li
        = link_to "Details", build_path(build)

      - if can? :delete, build
        %li
          = link_to "Delete", build_path(build), :method => :delete, :confirm => "Are you sure?"
  .block_content
    %div.small.left
      %strong Queued:
      = build.created_at
      %br/
      %strong Started:
      = build.started_at
      %br/
      %strong Completed:
      = build.completed_at
      - if build.completed_at
        %br/
        %strong Duration:
        = distance_of_time_in_words(build.started_at, build.completed_at)
      %br/
      %strong Author:
      = build.latest_commit.nil? ? "waiting" : build.latest_commit.author
      %br/
      %strong Commit:
      - if build.latest_commit.nil?
        = "waiting"
      - else
        - if build.latest_commit.url.nil?
          = build.latest_commit.guid
        - else
          = link_to build.latest_commit.guid, build.latest_commit.url,
          :target => :_blank
      %br/
      %strong Branch:
      = build.latest_commit.nil? ? build.project.branch_name : build.latest_commit.branch
    %div.small.right
      %strong ID:
      = build.id
      %br/
      %strong Build Steps:
      = build.project.steps.count
      %br/
      %strong Steps Completed:
      = (build.steps_completed > 0) ? build.steps_completed : 'waiting'
      %br/
      %strong Author Email:
      = build.latest_commit.nil? ? "waiting" : build.latest_commit.author_email
      %br/
      %strong Message:
      = build.commits.present? ? build.commits.last.message : "waiting"

  .bendl
  .bendr

app/views/builds/latest_builds.html.haml
- @builds.each do |build|
  = render build

app/views/builds/show.html.haml
- @build.build_steps.asc(:started_at).each do |step|
  .block
    .block_head
      .bheadl
      .bheadr
      %h2= step.name
    .block_content
      - if step.success? or step.failed?
        .pre= step.clean_output.html_safe
      - else
        .pre= "...building..."
    .bendl
    .bendr