config/routes.rb
Bob::Application.routes.draw do

  devise_for :users

  resources :dashboards
  resources :projects
  resources :builds
  resources :users

  match "/projects/:id/build", :to => "projects#build",:as=> :build_project
  match "/projects/:id/delete_step", :to => "projects#delete_step", :as => :delete_step
  match "/build/:id/status", :to => "builds#build_status", :as => :build_status
  match "/list", :to => "builds#latest_builds", :as => :latest_builds
  match "/list(/:id)", :to => "builds#latest_by_project", :as => :latest_by_project

  resources :service do
    post 'github'
  end

  root :to => "dashboards#index"
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field   :name,              :type => String
  field   :scm_type,          :type => String,  :default => 'Bob::Git'
  field   :scm_path,          :type => String
  field   :keep_build_count,  :type => Integer, :default => 10 
  field   :fixed_branch,      :type => Boolean, :default => false
  field   :branch_name,       :type => String,  :default => 'master'
  field   :private,           :type => Boolean, :default => false
  slug    :name

  index :branch_name
  index :scm_path
  index :name

  references_many :builds, :dependent => :delete
  references_many :commits, :dependent => :delete
  references_many :users, :stored_as => :array, :inverse_of => :projects
  embeds_many :steps
  embeds_one :campfire, :class_name => 'Notifier::Campfire'

  validates_presence_of :name
  validates_presence_of :scm_path
  validates_presence_of :keep_build_count

  validates_associated :steps
  validates_associated :campfire
  accepts_nested_attributes_for :steps
  accepts_nested_attributes_for :campfire


  # public only projects
  scope :public_projects, where(:private => false)

  # public or where user is allowed
  scope :allowed_projects, lambda { |user| any_of({:user_ids.in => [user.id]}, {:private => false})  }

  # run the build
  def build!
    build = Build.create(:project => self)
    build.delay.perform unless has_running_builds?
  end

  def has_running_builds?
    self.builds.where(:state => :building).count > 0 ? true : false
  end

  def total_builds
    (builds.count + builds.deleted.count)
  end

  def fail_rate
    failed_deleted = builds.deleted.where(:state => 'failed').count
    failed  = builds.where(:state => 'failed').count 

    fail_count = failed_deleted + failed
    (fail_count.to_f / total_builds.to_f) * 100
  end
       
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :find_project, :only => [:destroy, :edit, :update, :build, :delete_step]
  load_and_authorize_resource :except => [:create]

  # index, lookup all the sources
  def index
    @projects = Project.paginate :page => params[:page], :per_page => 20
  end

  def new
    @project = Project.new
    @project.build_configs.build
    ap @project.build_configs.steps
    @project.build_campfire

  end

  def create
    params[:project][:user_ids].delete_if {|x| x.blank? }

    @project = Project.new(params[:project])
    respond_to do |format|
      if @project.save
        format.html { redirect_to(projects_path, :notice => 'Project created.') }
      else
        format.html { render :action => "new" }
      end
    end
    authorize! :create, @project
  end

  def destroy
    @project.destroy
    redirect_to(projects_path)
  end

  def edit
    if @project.campfire
      @project.campfire = Notifier::Campfire.new
    end
  end

  def update
    params[:project][:user_ids].delete_if {|x| x.blank? }

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(projects_url, :notice => "Project updated.") }
      else
        format.html { render :action => "edit" }
      end
    end
  end
 
  def build
    if @project.has_running_builds?
      flash[:error] = "Build already running for #{@project.name} try again in a few minutes."
      redirect_to(dashboards_url)
    else
      @project.build!
      redirect_to(dashboards_url, :notice => "Build request sent.")
    end
    authorize! :update, @project
  end

  def delete_step 
    @step = @project.steps.find(params[:step])
    @step.destroy
    render :text => 'ok'
  end

  def find_project
    @project = Project.where(:slug => params[:id]).first
  end
  private :find_project
  
end

app/views/projects/_form.html.haml
- if project.errors.any?
  .block
    .block_head
      .bheadl
      .bheadr
      %h2 ERRORS
    .block_content
      #error_explanation
        %h2= "#{pluralize(project.errors.count, "error")} prohibited this project from being saved:"
        %ul
          - project.errors.full_messages.each do |msg|
            %li= msg
    .bendl
    .bendr

= simple_form_for project do |f|
  .block.small.left
    .block_head
      .bheadl
      .bheadr
      %h2
        = form_name
        = " - " unless project.new_record?
        = link_to "BUILD", build_project_path(project) unless project.new_record?
      %span.ajax-loading
      %ul
        %li
          /= link_to "Add Source", new_project_path unless new_record?
    / .block_head ends
    .block_content
      = f.label 'Project Id'
      = project.id
      %p
      = f.input :name, :input_html => {:class => :text }
      %p
      = f.input :scm_path, :input_html => {:class => :text }
      %p
      = f.input :branch_name, :input_html => {:class => :text }
      %p
      = f.input :keep_build_count, :input_html => {:class => :text }
      /%p
      /= f.check_box :fixed_branch, :class => :checkbox
      /= f.label :fixed_branch
      %p
      = f.check_box :private, :class => :checkbox
      = f.label :private
      %p
        = f.association :users, :collection => User.any_in(:role => ['client', 'admin']), :as => :check_boxes
      %p
    .bendl
    .bendr

  .block.small.right
    .block_head
      .bheadl
      .bheadr
      %h2 
        = image_tag('notifications/campfire.png', :width => 22, :height => 22) 
        Campfire
    .block_content
      %h3
        = f.simple_fields_for :campfire do |cf|
          = cf.input :token, :input_html => {:class => :text}
          %p 
          = cf.input :room, :input_html => {:class => :text}
          %p 
          = cf.input :subdomain, :input_html => {:class => :text}
          %p 
          = cf.check_box :ssl, :class => :checkbox
          = cf.label :ssl


    .bendl
    .bendr

  .block.small.right
    .block_head
      .bheadl
      .bheadr
      %h2 
        = image_tag('mail.png', :width => 22, :height => 22) 
        Email
    .block_content
      %h3 Coming Soon
      

    .bendl
    .bendr

  = f.simple_fields_for :build_configs do |config|
    .block.config
      .block_head
        .bheadl
        .bheadr
        %h2 Config
      .block_content
        = config.input :name, :input_html => {:class => 'text config_name'}
        %p
        = config.input :env_cmd, :as => :text
        %p
        = config.simple_fields_for :steps do |step|
          %div.build-steps
            %div.build-step
              %h2{:style => "border-bottom: 1px solid"} Step #1
              = step.input :name, :input_html => {:class => :text}
              %p
              = config.input :command, :as => :text
            %p
              = link_to 'Add Step', '#', :class => 'add-step'

      .bendl
      .bendr
  = f.button :submit, :class => "submit mid"
  %p
:javascript
    /*
    $(function() {
      $('.command').each(function() {
        command     = $(this).val().split(/\r\n|\r|\n/);
        parent_div  = $(this).parent().parent();
        pre_area    = parent_div.find('.pre:first');
        pre_area.html(command.join(' && '));
      });
    });
    */
    $(function() {

      // update the config names on load
      $('.config_name').each(function() {
        var config_name = $(this).val();
        parent_div = $(this).parents()[2];
        h2 = $(parent_div).find(' .block_head h2:first');
        (config_name != '') ? h2.html(config_name) : 'CONFIG'
      });

      // update the config on change/keyup
      $('.config_name').live('keyup', function() {
        var config_name = $(this).val();
        parent_div = $(this).parents()[2];
        h2 = $(parent_div).find(' .block_head h2:first');
        h2.html(config_name);
      });

      $('a.add-step').live('click', function(e) {
        e.preventDefault();
        var first = $('.build-step:first').clone();
        $(this).before('<p></p>');
        $(this).before(first);
        $('body').animate({scrollTop: $('body').attr('scrollHeight')}); 

        step = 1;
        $('.build-step h2').each(function() {
          $(this).html('Step #' + step);
          step++;
        });

      });
      
    });

app/views/projects/_project.html.haml
%tr{:id => "project_#{project.id}"}
  %td= project.name
  %td= project.scm_path
  %td= project.branch_name
  %td.center= project.total_builds
  %td.center= (project.total_builds > 0) ? number_to_percentage(project.fail_rate, :precision => 0) : "n/a"
  %td.center
    = image_tag("lock.png", :width => 16, :height => 16, :alt => 'Private', :title => 'Private') if project.private
  %td
    = image_tag(Notifier::Campfire.icon, :width => 16, :height => 16, :alt => 'Campfire', :title => 'Campfire') if project.campfire.post_message?
    /= image_tag("mail.png", :width => 16, :height => 16, :alt => 'Campfire', :title => 'Campfire') if project.campfire.post_message?
  %td.actions
    = link_to "Build", build_project_path(project)
    |
    = link_to "Edit", edit_project_path(project)
    |
    = link_to "Delete", project_path(project), :confirm => "Are you sure?", :method => :delete

app/views/projects/edit.html.haml
= render :partial => 'form', :locals => {:form_name => 'Edit Project', :project => @project }

app/views/projects/index.html.haml
.block
  .block_head
    .bheadl
    .bheadr
    %h2 Projects
    %span.ajax-loading
    %ul
      %li
        = link_to "Add Project", new_project_path
  / .block_head ends
  .block_content
    %form{:action => "", :method => "post"}
      %table{:cellpadding => "0", :cellspacing => "0", :width => "100%", :id => "users"}
        %tr
          %th Name
          %th Path
          %th Branch
          %th Total Builds 
          %th.center Fail Rate
          %th Private?
          %th Notifiers
          %td &nbsp;
        - @projects.each do |project|
          = render project

      / pagination
      /= will_paginate @projects
      
  / .block_content ends
  .bendl
  .bendr

app/views/projects/new.html.haml
= render :partial => 'form', :locals => {:form_name => 'Add Project', :project => @project }