config/routes.rb
Bob::Application.routes.draw do

  devise_for :users

  resources :dashboards
  resources :projects
  resources :builds
  resources :users

  match "/projects/:id/build", :to => "projects#build",:as=> :build_project
  match "/projects/:id/delete_step", :to => "projects#delete_step", :as => :delete_step
  match "/build/:id/status", :to => "builds#build_status", :as => :build_status
  match "/list", :to => "builds#latest_builds", :as => :latest_builds
  match "/list(/:id)", :to => "builds#latest_by_project", :as => :latest_by_project

  resources :service do
    post 'github'
  end

  root :to => "dashboards#index"
end

app/views/layouts/_flash.html.haml
%div.message{:class => msg_type }
  %p= flash[msg_type]

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %title 
      BOB (BUILDER) ● 
      = params[:controller].to_s.capitalize
    %style{:media => "all", :type => "text/css"}
      @import url("/stylesheets/style.css");
      @import url("/stylesheets/date_input.css");
    /[if IE] <meta http-equiv="X-UA-Compatible" content="IE=7" />
    /[if lt IE 8] <style type="text/css" media="all">@import url("/stylesheets/ie.css");</style>
    /[if IE] <script type="text/javascript" src="/javascripts/excanvas.js"></script>
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js", :type => "text/javascript"}
    = javascript_include_tag 'jquery.inlineedit', 'jquery.select_skin', 'custom', 'rails.js', 'application.js'
    = csrf_meta_tag
  %body
    #hld
      .wrapper
        / wrapper begins
        #header
          .hdrl
          .hdrr
          %h1
            %a{:href => "#"} BOB (BUILDER)
          %ul#nav
            %li
              = link_to "Dashboard", dashboards_path  
            - if can? :manage, Project
              %li{:class => current_page?("admin/sources") ? "active":""}
                = link_to "Projects", projects_url
            - if can? :manage, User
              %li
                = link_to "Users", users_url
          %p.user
            / User login info
            - if current_user
              = current_user.name
              = " | "
              = link_to "Logout", destroy_user_session_path
            - else
              = link_to "Log In", new_user_session_path, :class => 'login'
        - [:error, :warning, :notice, :info].each do |msg_type|
          = render :partial => "layouts/flash", :locals => {:msg_type => msg_type, :flash => flash} unless flash[msg_type.to_sym].blank?
        #builds
          = yield
        
        #footer
          %strong Version: 
          = BOB::VERSION
          = " | "
          = link_to "GitHub Repo", "https://github.com/zenom/BOB", :target => :_blank
      / wrapper ends
    / #hld ends